# /// script
# requires-python = ">=3.11"
# dependencies = ["PyYAML>=6,<7"]
# ///
"""Refresh both README catalogs and their generated SVG skill headers."""

from pathlib import Path
import argparse
from hashlib import sha256
from html import escape
import re
import sys
import xml.etree.ElementTree as ET

import yaml

ROOT = Path(__file__).resolve().parents[1]
START = "<!-- skills:start -->"
END = "<!-- skills:end -->"
ASSETS = ROOT / "docs" / "assets" / "catalog"
GENERATED = "<!-- Generated by scripts/update_catalog.py. -->"
REPOSITORY = "https://github.com/smturtle2/codex-skills"


def metadata(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"\A---\r?\n(.*?)\r?\n---(?:\r?\n|$)", text, re.S)
    if not match:
        raise ValueError(f"Missing skill frontmatter: {path.relative_to(ROOT)}")
    data = yaml.safe_load(match[1])
    if not isinstance(data, dict):
        raise ValueError(f"Invalid skill frontmatter: {path.relative_to(ROOT)}")
    for field in ("name", "description"):
        if not isinstance(data.get(field), str) or not data[field].strip():
            raise ValueError(f"Missing {field}: {path.relative_to(ROOT)}")
    if data["name"] != path.parent.name or not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", data["name"]):
        raise ValueError(f"Skill name must match its lowercase folder name: {path.relative_to(ROOT)}")
    return data


def summary(guide: Path, fallback: str) -> str:
    if guide.exists():
        # The first paragraph after the title is also the catalog description.
        match = re.search(r"^# [^\n]+\n\s*\n([^\n]+(?:\n[^\n]+)*)", guide.read_text(encoding="utf-8"), re.M)
        if match:
            return " ".join(match[1].split())
    return " ".join(fallback.split())


def install_prompt(name: str) -> str:
    guide = ROOT / "docs" / "skills" / f"{name}.md"
    prompt = f"Use $skill-installer to install skills/{name} from {REPOSITORY}."
    if guide.exists():
        # Reuse the guide's first install block, including companion skills.
        match = re.search(r"```text\n(Use \$skill-installer to install [^`]+)\n```", guide.read_text(encoding="utf-8"))
        if match:
            prompt = match[1].strip()
    # Keep repository URLs and companion skill names visible on narrow screens.
    match = re.fullmatch(
        r"Use \$skill-installer to install (skills/[a-z0-9-]+(?: and skills/[a-z0-9-]+)*) from (https://\S+?)\.?",
        prompt,
    )
    if match:
        names = ", ".join(part.removeprefix("skills/") for part in match[1].split(" and "))
        return f"Use $skill-installer.\nRepository:\n{match[2]}\nInstall from skills/:\n{names}"
    return prompt


def skill_art(path: Path, data: dict) -> str:
    name = data["name"]
    palettes = [
        ("#F0ECFF", "#7556CC"), ("#E6F3EE", "#238368"),
        ("#FFF0E4", "#C36C34"), ("#E8F0FF", "#4669C5"),
        ("#FBE9F1", "#BC547D"),
    ]
    bg, accent = palettes[int(sha256(name.encode()).hexdigest()[:8], 16) % len(palettes)]
    icon = path.parent / "assets" / "icon.svg"
    if icon.exists():
        svg = ET.fromstring(icon.read_text(encoding="utf-8"))
        svg.set("x", "32")
        svg.set("y", "40")
        svg.set("width", "88")
        svg.set("height", "88")
        ET.register_namespace("", "http://www.w3.org/2000/svg")
        artwork = ET.tostring(svg, encoding="unicode")
    else:
        # New skills need no custom artwork to get the same header layout.
        artwork = f'''<g transform="translate(32 40)">
  <rect width="88" height="88" rx="20" fill="white"/>
  <g fill="none" stroke="{accent}" stroke-width="3">
    <rect x="20" y="20" width="18" height="18" rx="4"/>
    <rect x="50" y="20" width="18" height="18" rx="4"/>
    <rect x="20" y="50" width="18" height="18" rx="4"/>
    <path d="M50 59h18m-9-9v18"/>
  </g>
</g>'''
    font_size = min(44, int(600 / (0.63 * len(name))))
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="960" height="168" viewBox="0 0 960 168" role="img" aria-labelledby="label">
{GENERATED}
<title id="label">{escape(name)}</title>
<defs><clipPath id="bounds"><rect width="960" height="168" rx="16"/></clipPath></defs>
<g clip-path="url(#bounds)">
  <rect width="960" height="168" fill="{bg}"/>
  <rect x="1" y="1" width="958" height="166" rx="15" fill="none" stroke="{accent}" stroke-opacity=".15"/>
  <g fill="none" stroke="{accent}" stroke-width="2" opacity=".2" transform="translate(824 -18) rotate(18)">
    <rect width="112" height="112" rx="24"/>
    <rect x="28" y="28" width="112" height="112" rx="24"/>
    <rect x="56" y="56" width="112" height="112" rx="24"/>
  </g>
  {artwork}
  <text x="148" y="68" fill="{accent}" font-family="Arial, sans-serif" font-size="13" font-weight="700" letter-spacing="2.5">CODEX SKILL</text>
  <text x="146" y="111" fill="#242735" font-family="ui-monospace, SFMono-Regular, Consolas, monospace" font-size="{font_size}" font-weight="700">{escape(name)}</text>
</g>
</svg>
'''


def catalog(skills: list[tuple[Path, dict]], korean: bool) -> str:
    entries = []
    for path, data in skills:
        name = data["name"]
        source = path.relative_to(ROOT).as_posix()
        guide = ROOT / "docs" / "skills" / f"{name}{'.ko' if korean else ''}.md"
        links = [("지침" if korean else "Instructions", source)]
        if guide.exists():
            links.insert(0, ("사용 가이드" if korean else "Guide", guide.relative_to(ROOT).as_posix()))
        description = summary(guide, data["description"])
        entries.append(
            f'<a id="{name}"></a>\n\n'
            f'<img src="docs/assets/catalog/{name}.svg" width="960" alt="{name}">\n\n'
            f"{description}\n\n"
            f"```text\n{install_prompt(name)}\n```\n\n"
            + " · ".join(f"[{label}]({url})" for label, url in links)
        )
    if not entries:
        return "아직 등록된 스킬이 없습니다." if korean else "No skills are listed yet."
    navigation = '<p align="center">\n' + " · ".join(
        f'<a href="#{data["name"]}">{data["name"].replace("-", "&#8209;")}</a>' for _, data in skills
    ) + "\n</p>"
    return navigation + "\n\n---\n\n" + "\n\n---\n\n".join(entries)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report stale catalogs without changing files")
    args = parser.parse_args()
    try:
        skills = [(path, metadata(path)) for path in sorted((ROOT / "skills").glob("*/SKILL.md"))]
        updates = []
        expected = {ASSETS / f'{data["name"]}.svg': skill_art(path, data) for path, data in skills}
        for path, new in expected.items():
            old = path.read_text(encoding="utf-8") if path.exists() else None
            if old is not None and GENERATED not in old:
                raise ValueError(f"Refusing to overwrite an unmanaged asset: {path.relative_to(ROOT)}")
            if old != new:
                updates.append((path, new))
        obsolete = [path for path in ASSETS.glob("*.svg") if path not in expected and GENERATED in path.read_text(encoding="utf-8")]
        for filename, korean in (("README.md", False), ("README.ko.md", True)):
            path = ROOT / filename
            old = path.read_text(encoding="utf-8")
            if old.count(START) != 1 or old.count(END) != 1 or old.index(START) > old.index(END):
                raise ValueError(f"Expected one ordered catalog marker pair in {filename}")
            before, rest = old.split(START, 1)
            _, after = rest.split(END, 1)
            new = before + START + "\n\n" + catalog(skills, korean) + "\n\n" + END + after
            if old != new:
                updates.append((path, new))
        # Prepare both languages and assets before writing any changes.
        if args.check:
            for path, _ in updates:
                print(f"Stale catalog: {path.relative_to(ROOT)}", file=sys.stderr)
            for path in obsolete:
                print(f"Obsolete generated asset: {path.relative_to(ROOT)}", file=sys.stderr)
            if updates or obsolete:
                return 1
        else:
            for path, new in updates:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(new, encoding="utf-8")
                print(f"Updated {path.relative_to(ROOT)}")
            for path in obsolete:
                path.unlink()
                print(f"Removed {path.relative_to(ROOT)}")
        print(f"Catalogs cover {len(skills)} skills.")
        return 0
    except (OSError, ValueError, yaml.YAMLError, ET.ParseError) as error:
        print(f"Catalog error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
